notifications:
  email: false
language:
- cpp
addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - libopenal-dev
    - libjpeg-dev
    - libudev-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - libxcursor-dev
  homebrew:
    packages:
     - cmake
    update: true
matrix:
  include:

  - name: "Ubuntu Bionic 18.04 GCC"
    os: linux
    dist: bionic
    compiler: gcc

  - name: "Ubuntu Bionic 18.04 Clang"
    os: linux
    dist: bionic
    compiler: clang
  - name: "macOS 10.14 GCC"

    os: osx
    osx_image: xcode11.3
    compiler: gcc
  - name: "macOS 10.14 Clang"

    os: osx
    osx_image: xcode11.3
    compiler: clang

  - name: "Windows"
    os: windows

install:
- git clone https://github.com/SFML/SFML.git
- cd SFML
- mkdir install
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_INSTALL_FRAMEWORK_PREFIX=../install -DSFML_BUILD_FRAMEWORKS=FALSE -DBUILD_SHARED_LIBS=TRUE ..
- cmake --build . --config Release --target install
- cd ../../
script:
- mkdir install/
- mkdir install/IdleRomanEmpire
- cmake -DCMAKE_INSTALL_PREFIX=./install/IdleRomanEmpire -DSFML_DIR=./SFML/install/lib/cmake/SFML .
- cmake --build . --config Release --target install
