notifications:
  email: false
language:
- cpp
addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - libopenal-dev
    - libjpeg-dev
    - libudev-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - libxcursor-dev
  homebrew:
    packages:
     - cmake
    update: true
matrix:
  include:

  - name: "Ubuntu Bionic 18.04 GCC"
    os: linux
    dist: bionic
    compiler: gcc

  - name: "Ubuntu Bionic 18.04 Clang"
    os: linux
    dist: bionic
    compiler: clang
  - name: "macOS 10.14 GCC"

    os: osx
    osx_image: xcode11.3
    compiler: gcc
  - name: "macOS 10.14 Clang"

    os: osx
    osx_image: xcode11.3
    compiler: clang

  - name: "Visual Studio 16 2019 Dynamic"
    os: windows
    env:
      - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
      - VS160COMNTOOLS="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools"
      - PATH=$MSBUILD_PATH:$PATH
    install:
      - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
      - choco install visualstudio2019-workload-nativedesktop


install:
- git clone https://github.com/SFML/SFML.git
- cd SFML
- mkdir install
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_INSTALL_FRAMEWORK_PREFIX=../install -DSFML_BUILD_FRAMEWORKS=FALSE -DBUILD_SHARED_LIBS=TRUE ..
- cmake --build . --config Release --target install
- cd ../../
script:
- mkdir install/
- mkdir install/IdleRomanEmpire
- cmake -DCMAKE_INSTALL_PREFIX=./install/IdleRomanEmpire -DSFML_DIR=./SFML/install/lib/cmake/SFML .
- cmake --build . --config Release --target install
