notifications:
  email: false

language: cpp

branches:
  only:
    - master

addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - libopenal-dev
    - libjpeg-dev
    - libudev-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - libxcursor-dev
    update: true

matrix:
  include:
    - name: "Ubuntu Focal 20.04 GCC"
      os: linux
      dist: focal
      compiler: gcc

    - name: "Ubuntu Focal 20.04 Clang"
      os: linux
      dist: focal
      compiler: clang

    - name: "Windows"
      os: windows

before_install:
  - eval "${MATRIX_EVAL}"

install:
- git clone https://github.com/SFML/SFML.git
- cd SFML
- mkdir install
- mkdir build
- cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_INSTALL_FRAMEWORK_PREFIX=./install -DSFML_BUILD_FRAMEWORKS=FALSE -DBUILD_SHARED_LIBS=TRUE
- cmake --build ./build --config Release --target install
- cd ..

script:
- mkdir build
- mkdir install
- cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=TRUE -DCMAKE_INSTALL_PREFIX=./install -DSFML_DIR=./SFML/install/lib/cmake/SFML
- cmake --build ./build --config Release --target install
- cmake --build ./build --config Release --target IRERunTests
