name: IRE_cpp
on: [push, pull_request]

env:
  REPO: IdleRomanEmpire
  GITHUB_REPO: Kubaaa96/IdleRomanEmpire 

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest


  windows:
    name: Windows
    runs-on: windows-latest
    env:
      platform: x64
      VCPKG_DEFAULT_TRIPLET: x64-windows
      GENERATOR: "Visual Studio 16 2019"
      ARCH: "x64"
      CMAKE_TOOLCHAIN_FILE: "C:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
      CMAKE_INSTALL_PREFIX: "C:\\install\\IdleRomanEmpire"
      WORKDIR:  "D:\\a\\IdleRomanEmpire\\IdleRomanEmpire\\"
      MSBUILD:  "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin"
    strategy:
      matrix:
        CONFIG: [Debug, Release]
        steps:
      - name: Update PATH
        run: |
          echo "::add-path::$Env:MSBUILD"
      - name: Cache vcpkg packages
        uses: actions/cache@v1
        id: cache-vcpkg-packages
        with:
          path: C:/vcpkg/packages
          key:  vcpkg-packages-45e5a67

      - name: Cache vcpkg installed
        uses: actions/cache@v1
        id: cache-vcpkg-installed
        with:
          path: C:/vcpkg/installed
          key:  vcpkg-installed-45e5a67

      - name: Clone the git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      
      - name: Install SFML
        run: |
          vcpkg install sfml:x64-windows
          vcpkg update
      - name: vcpkg integrate install
        run: vcpkg integrate install

      - name: Configure
        run: cmake . -Bbuild
                    -G "${env:GENERATOR}"
                    -A "${env:ARCH}"
                    -DCMAKE_TOOLCHAIN_FILE="${env:CMAKE_TOOLCHAIN_FILE}"
                    -DCMAKE_INSTALL_PREFIX="${env:CMAKE_INSTALL_PREFIX}"

      - name: Build
        run: msbuild build/ALL_BUILD.vcxproj /property:Configuration=${{ matrix.CONFIG }} /verbosity:minimal /m

      - name: Configure
        run: cmake . -Bbuild
                    -G "${env:GENERATOR}"
                    -A "${env:ARCH}"
                    -DCMAKE_TOOLCHAIN_FILE="${env:CMAKE_TOOLCHAIN_FILE}"
                    -DCMAKE_INSTALL_PREFIX="${env:CMAKE_INSTALL_PREFIX}"
                    -DBUILD_TESTS=TRUE

      - name: Tests
        working-directory: build
        run: ctest -C ${{ matrix.CONFIG }} --output-on-failure --timeout 540

      - name: Install
        working-directory: build
        run: msbuild INSTALL.vcxproj /verbosity:minimal /m

